services:
  postgres:
    image: postgres:13
    container_name: talung-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change-me-PleaseReplace
    ports:
      - "15432:5432"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - talung-sso-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: talung-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change-me-PleaseReplace
      KC_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "18080:8080"
    volumes:
      - ./docker/keycloak/themes:/opt/keycloak/themes
      - ./database/keycloak:/opt/keycloak/data
    networks:
      - talung-sso-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

networks:
  talung-sso-net:
    driver: bridge